# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectSet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'PureLayout'

  # Pods for ProjectSet

  target 'ProjectSetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectSetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
